# Generated by Django 3.1 on 2020-08-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200812_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='backend.student'),
        ),
    ]
